-- 테이블 삭제
DROP TABLE PROCEEDING;
DROP TABLE EMPLOYEE;
DROP TABLE PJT;
DROP TABLE DEPARTMENT;

-- 부서 테이블 생성
CREATE TABLE DEPARTMENT (
    DEPT_NO       VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME     VARCHAR2(30 BYTE) NULL,
    DEPT_LOCATION VARCHAR2(50 BYTE) NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY(DEPT_NO)
);
-- 프로젝트 테이블 생성
CREATE TABLE PJT (
    PJT_NO      NUMBER            NOT NULL,
    PJT_NAME    VARCHAR2(30 BYTE) NULL,
    BEGIN_DATE  DATE              NULL,
    END_DATE    DATE              NULL,
    CONSTRAINT PK_PJT PRIMARY KEY(PJT_NO)
);
-- 사원 테이블 생성
CREATE TABLE EMPLOYEE (
    EMP_NO     NUMBER            NOT NULL,
    DEPT_NO    VARCHAR2(15 BYTE) NOT NULL,
    POSITION   CHAR(10 BYTE)     NULL,
    NAME       VARCHAR2(15 BYTE) NULL,
    HIRE_DATE  DATE              NULL,
    SALARY     NUMBER            NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMP_NO),
    CONSTRAINT EMPLOYEE_DEPARTMENT_FK FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO)
);
-- 프로젝트진행 테이블 생성
CREATE TABLE PROCEEDING (
    PCD_NO  NUMBER NOT NULL,
    EMP_NO  NUMBER NOT NULL,
    PJT_NO  NUMBER NOT NULL,
    CONSTRAINT PK_PROCEEDING_PK PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_PROCEEDING_EMPLOYEE FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
    CONSTRAINT FK_PROCEEDING_PJT FOREIGN KEY(PJT_NO) REFERENCES PJT(PJT_NO)
);