DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD(
    BOARD_NO NUMBER NOT NULL,
    TITLE       VARCHAR2(100 BYTE) NOT NULL,
    CONTENT     VARCHAR2(400 BYTE), 
    CREATE_DATE DATE,
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

COMMIT;